---
- hosts: all
  become: 
  tasks: 
  - name: install webserver on ubuntu ansible nodes
    apt: 
      name: apache2 
      state: present

  - name: i want to start start webserver 
    service: 
         name: apache2 
         state: started 
             
    

 
    
    
   