---
- hosts: all
  become: 
  tasks: 
  - name: install webserver on ubuntu ansible nodes
    apt: 
      name: apache2 
      state: present 

  - name: start webserver on ubuntu anssible nodes
    service: 
      name: apache2 
      state: started     