---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2 web server 
    apt: 
       name: apache2 
       state: present 

  - name: i want to start webserver 
    services: 
         name: apache2
         state: started      